### ISSUE TITLE
I keep getting an error 500 from the API server

### ISSUE THREAD

**Issue by ksegla** [nadermx/backgroundremover#106]
Hi
The server seems down. And I'm not getting any answers from the support, despite sending 2 mails. The javascript code example isn't working and the server keeps returning error 500

**Comment by nadermx** [comment]
let me check

**Comment by xzitlou** [comment]
@ksegla we have reviewed the code, and indeed, we had an issue with the API when uploading files. The error has been corrected, so you can try again now. Tx
