### ISSUE TITLE
portrait got wrong orientation after bg removed

### ISSUE THREAD

**Issue by gmmp** [nadermx/backgroundremover#107]
Hello, i have to say, this is a great project, really help my work, thank you. But recently we ran into a problem, it's similar to a [closed issue](https://github.com/nadermx/backgroundremover/issues/16).

One of our customer's portrait is in a wrong orientation after bg removed. I tried both option "Objects, Humans, or Things" and "Only Humans" on the official tool website, tried all models (u2net, u2net_human_seg, u2netp) by running python cmd, they got same result. Is there any cmd option i could use to fix that?

I also notice that the original picture is attched with EXIF info, but output one is not.
![image](https://github.com/nadermx/backgroundremover/assets/16728548/9fc12b51-2302-4cc0-9c88-acd6c00c80bd)

**Comment by nadermx** [comment]
Try putting a black frame around the picture

**Comment by gmmp** [comment]
> Try putting a black frame around the picture

Thank you, work like a charm!
