### ISSUE TITLE
Subscription API

### ISSUE THREAD

**Issue by tannusesquerdo** [nadermx/backgroundremover#109]
Hello Guys,

I hope you are doing well. I am trying to make a subscription for the API, but I can't complete the verification process because the verification e-mail is not being sent to the email. Can you guys check? 

Sorry to Open the issue here; I tried the contact page, and there is no answer yet.

**Comment by xzitlou** [comment]
Hello @tannusesquerdo , let me check the issue, meanwhile I will send you the verification code to your email address

**Comment by xzitlou** [comment]
@tannusesquerdo just to let you know that the problem is fixed
