### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by Alex-Bujorianu** [nadermx/backgroundremover#111]
The ANTIALIAS field was removed in Pillow versions 10.0 and above.

**Comment by nadermx** [comment]
run  `pip install --upgrade moviepy` 
https://github.com/Zulko/moviepy/commit/e163cf53a4d9d82a5697ee8d02099f91dc241cc9

**Comment by LineCatOvO** [comment]
While I also tried update moviepy to the latest, it is still calling error, I changed that to LANCZOS manually and now it seems working fine. Well this might be a bug of moviepy?

**Comment by nadermx** [comment]
I believe so, which is odd though as moviepy seems to have have a added try
except already for it.  So maybe they didn't bump the version to the commit
I showed.
