### ISSUE TITLE
backgroundremoverai.com  application behavior changed is unsuitable for us now

### ISSUE THREAD

**Issue by bt-dev** [nadermx/backgroundremover#118]
We had tested the behavior of the application and found it suitable for our requirements a few weeks back.

We then purchased 300 credits and programmatically used it with the files. The new output files have a shadow around the pictures -- which is not suitable for us.

Attached is a zip containing the original images, the earlier output from the application and the new one.

Let us know how we can get the "earlier images" output.
[backgroundremoval.zip](https://github.com/nadermx/backgroundremover/files/13741434/backgroundremoval.zip)

 
Thanks & Regards,

**Comment by nadermx** [comment]
There are different algorithms you can try.  Perhaps when you tried the first iteration you tried the u2net, then u2net_humans.  As they give different results.  We haven't updated the algorithm in terms of actual background removal
