### ISSUE TITLE
The issue of “failed with exit status 2”

### ISSUE THREAD

**Issue by sw8207** [nadermx/backgroundremover#12]
Hi nadermx and everyone

I try to run the backgroundremover on windows. My version is python 3.6 64bit. I have the following problems. 

I have reinstalled the Visual Studio. The error still occurs. 

........................
File "d:\backgroundremover-main\lib\site-packages\numpy\distutils\ccompiler.py", line 174, in CCompiler_spawn
    (cmd, s, msg))
distutils.errors.DistutilsExecError: Command "D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W
3 /GL /DNDEBUG /MT -DPYCC_MODULE_NAME=aot -DPYCC_USE_NRT=1 -Id:\backgroundremover-main\include -ID:\Program Files\Python36\include -ID:\Program Files\Python36\include -Id:\\ba
ckgroundremover-main\\lib\\site-packages\\numpy\\core\\include -ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcd:\backgro
undremover-main\lib\site-packages\numba\pycc\modulemixin.c /FoC:\Users\sw820\AppData\Local\Temp\pycc-build-aot-2_frh03u\backgroundremover-main\lib\site-packages\numba\pycc\mod
ulemixin.obj" failed with exit status 2

During handling of the above exception, another exception occurred:

........................................
.......................................
  File "D:\Program Files\Python36\lib\distutils\_msvccompiler.py", line 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL
/DNDEBUG /MT -DPYCC_MODULE_NAME=aot -DPYCC_USE_NRT=1 -Id:\backgroundremover-main\include -ID:\Program Files\Python36\include -ID:\Program Files\Python36\include -Id:\\backgrou
ndremover-main\\lib\\site-packages\\numpy\\core\\include -ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcd:\backgroundrem
over-main\lib\site-packages\numba\pycc\modulemixin.c /FoC:\Users\sw820\AppData\Local\Temp\pycc-build-aot-2_frh03u\backgroundremover-main\lib\site-packages\numba\pycc\modulemix
in.obj" failed with exit status 2

**Comment by nadermx** [comment]
I have no windows system to use, but this might be the same issue as this, https://github.com/nadermx/backgroundremover/issues/8 

I'm unsure if you installed python3.x-dev (or what ever version of python you are using) and ffmpeg 4.4.

**Comment by nadermx** [comment]
try newest relase https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1
