### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by JuanjoCatalaGarrido** [nadermx/backgroundremover#121]
Pillow=>10.0 seems to have removed attribute "Image".

Downgrading to Pillow==9.5.0 seems to fix the bug

**Comment by GPTdomaine** [comment]
Its depriciated nowdays. In one project i was doing with PIL i found that; LANCZOS instead of ANTIALIAS works in my case and for my use case correct one would be PIL.Image.Resampling.LANCZOS instead of ANTIALIAS. Not sure how would it affect this project but you can give it a try

**Comment by nadermx** [comment]
I'll try this out in a few days

**Comment by nadermx** [comment]
closed in https://github.com/nadermx/backgroundremover/commit/ecd561b61f18bbdcbac48b4929a12bb6508a9d8f
