### ISSUE TITLE
Running backgroundremover on live server it take longer time and nothing happen and hanging the server.

### ISSUE THREAD

**Issue by alshugairi** [nadermx/backgroundremover#123]
I installed you project in local it worked fine but win i installed it as production and run command 

backgroundremover -i "/path/to/image.jpeg" -o "output.png"

it take long time and nothing happen and hanging the server.

**Comment by nenenna** [comment]
Yes, me too. Have you solved it?

**Comment by nadermx** [comment]
First time it runs if it doesn't have u2 net li rary it has to pull them.  So first run on a fresh install does take a bit.
