### ISSUE TITLE
How to use as a library ?

### ISSUE THREAD

**Issue by burakkaratasz** [nadermx/backgroundremover#129]
I want to import in an Android app

**Comment by ahmad88me** [comment]
I created it a pull request to use it as a python library https://github.com/nadermx/backgroundremover/pull/138. 

The easiest way to use it in Android is to create a webapp using this repo and maybe Flask or Django. Then you can expose APIs that you can call from your android app.

**Comment by nadermx** [comment]
Fixed in https://github.com/nadermx/backgroundremover/commit/123d4445808c25521d06611e6e7e3aa9bb426b2f read readme on how to tx @ahmad88me
