### ISSUE TITLE
Error initializing filter 'alphamerge' with args 'shortest=1'

### ISSUE THREAD

**Issue by osachub** [nadermx/backgroundremover#132]
I don't know why, but everytime when I try to create my video and I always get this error at last step:

```
[Parsed_alphamerge_1 @ 000001a3789c8d80] This filter does not take any options, but options were provided: shortest=1.
[AVFilterGraph @ 000001a377b2de80] Error initializing filter 'alphamerge' with args 'shortest=1'
Error initializing complex filters.
Invalid argument
```
My ffmpeg-6.1.1, also I try ffmpeg 4.4.0 too

How could I fix it? thanks

**Comment by osachub** [comment]
never mind, I removed all shortest=1 tag and fixed this problem myself

**Comment by nadermx** [comment]
what version of ffmpeg are you running?

**Comment by nadermx** [comment]
oh i see 4.4, that's odd.  Shortest was added in 4.4
