### ISSUE TITLE
Server Requirements?

### ISSUE THREAD

**Issue by daslicht** [nadermx/backgroundremover#139]
Hello,
what are the server requirements to run this **please**?
CPU ?
RAM ?

Cheers Marc

**Comment by nadermx** [comment]
Not sure to be honest.  Haven't seen how small of a box is required? Could maybe get away with running it on 1 cpu and 512 ram.  If you care to spin up a 1 core vps, 2 core, etc and see what works would be best.  Doesn't need a GPU to run, but will run much slower.

**Comment by daslicht** [comment]
Thank you!
