### ISSUE TITLE
Mismatch Between GitHub and PyPI Versions of backgroundremover v0.2.7

### ISSUE THREAD

**Issue by alexpovkolas** [nadermx/backgroundremover#142]
## Issue Description
There appears to be a discrepancy between the source code of `backgroundremover` v0.2.7 available on PyPI and the corresponding version on the GitHub repository.

## Details
The `bg.py` file from the PyPI package seems to be dated Dec 6, which does not match the latest version of the same file in the GitHub repository. This has led to some confusion and import issues when using backgroundremover as a library.

## Expected Behavior
The source code on PyPI should match the tagged release on GitHub for v0.2.7.

## Actual Behavior
The source code on PyPI for `backgroundremover` v0.2.7 includes an older version of `bg.py` from Dec 6, which is different from what's currently on GitHub.

## Steps to Reproduce
1. Install `backgroundremover` v0.2.7 via pip.
2. Compare the `bg.py` file from the installed package with the one available on the GitHub repository for the same version tag.

It would be greatly appreciated if the maintainers could look into this and ensure that the PyPI package is updated to reflect the GitHub repository's state for the same version.

Thank you for your attention to this matter.

**Comment by nadermx** [comment]
huh? The version on github is one commit ahead of the 0.2.7 release? I'm kinda of confused.

**Comment by alexpovkolas** [comment]
github is ok but PyPI has an issue. When you do `pip install backgroundremover==0.2.7` it fetches source code that does not match github 0.2.7 release. 
E.g. I don't have github.py file when install the lib via pip

**Comment by nadermx** [comment]
upgrade to 0.2.8 `pip install --upgrade backgroundremover`
