### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by PlXBCR** [nadermx/backgroundremover#154]
Hey I used API since few months, but it doesn't work anymore for 5 days.
I don't know why. It also bug on your website.

**Comment by nadermx** [comment]
Checking

**Comment by nadermx** [comment]
this should be fixed now

**Comment by PlXBCR** [comment]
Boss

**Comment by PlXBCR** [comment]
> Checking

Not fixed always a problem

**Comment by nadermx** [comment]
Yeah, the fix I did worked for a bit.  It's an issue with the box, working
on a fix
