### ISSUE TITLE
Pictures are -90 Degrees tilt

### ISSUE THREAD

**Issue by maxenium** [nadermx/backgroundremover#16]
Unfortunately some pictures you upload on backgroundremover.app are -90 Degrees tilt when they are processed. 

This happened when I uploaded a picture and choose the "Things option".

If you need a link to the picture don't hesitate contacting me.

**Comment by nadermx** [comment]
This seems to be mitigated by making a border around the image.  I may try and add in this feature on the next commit https://github.com/nadermx/backgroundremover/issues/38
