### ISSUE TITLE
M1 (Mac) PackagesNotFoundError: torchaudio

### ISSUE THREAD

**Issue by rcoenen** [nadermx/backgroundremover#17]
YEah that is a bit of a dead end right there....

**Comment by nadermx** [comment]
Try this? https://github.com/pytorch/audio

**Comment by rcoenen** [comment]
Thanks! OK I eventually got it to work on M1 macs... but oh my lord total package hell. And not just PyTorch audio it was..

**Comment by rcoenen** [comment]
Fixed, see here:
https://anaconda.org/ngam/torchaudio
