### ISSUE TITLE
Speed: Very slow processing and GPU hardly used?

### ISSUE THREAD

**Issue by rcoenen** [nadermx/backgroundremover#18]
Hi, OK I have successfully processed a 8 minute clip. It was a real slow process, and took a couple of hours.

How is it that Zoom en MS Teams can do basically the same job in real-time?

I have tried this on my M1 Mac but also on my PC with a GeFOrce GTX 1060 / 6 GB. (Yah I know this isn't mind-blowing but still, it's a proper GPU I'd reckon?) CUDA drivers all the latest. (V11.x)

In both cases, processing speeds were slow as molasses M1 and PC alike.

On PC I monitored the GPU usage and "Python" was never taking more than 1% of GPU resources available. Is that even right?
It feels it hardly use dteh CPU at all?

In any case, it feels that the whole process could be done much faster, near real time no, given Zoom, Teams etc can do it? WHere is the bottleneck?

**Comment by rcoenen** [comment]
Screenshot of what I am getting here. Actually no GPU seems to be used 


`backgroundremover -i .\me_recorded.mov -fr 30 -wn 2 -mk -o output.mp4`


![image](https://user-images.githubusercontent.com/753704/140103431-1951b8d2-3d19-4cd6-a463-24b88daa18bf.png)

**Comment by lue** [comment]
Had the same problem with no GPU use on Windows. Essentially pytorch was not installed properly. Was able to fix it by creating a clean conda environment with CUDA=11.3 using the command as recommended here: https://pytorch.org/get-started/locally/

`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`

**Comment by nadermx** [comment]
I have only used this on ubuntu.  I am slowly moving through some of these bugs and things i noticed where wrong.  I will see what I can do in order to try and speed it up more.  I am open to ideas as well or patches

**Comment by nadermx** [comment]
Try the newest version, I am getting consistently 30 fps with default options `pip install --upgrade backgroundremover`

**Comment by mindsocket** [comment]
The new Mac M1/M2 architecture doesn't use Nvidia CUDA. With pytorch 2.01 and I confirmed that "mps" is available...

```
>>> import torch
>>> torch.cuda.is_available()
False
>>> torch.backends.mps.is_available()
True
```

Knowing that I hacked `bg.py` and I was able to get my machine to use the Mac GPU and run significantly faster:

```
#DEVICE = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
DEVICE = torch.device('mps')
```

I'd submit a pull request to make this a 3-way check (cuda, mps or cpu) but am not sure I understand the version dependencies and nuances of pytorch to confidently say I've got it right for everyone.

**Comment by nadermx** [comment]
@mindsocket just applied a fix. i do 't have a mac, but did it fail before? Since I put a try/except.  If not i can do another validation
