### ISSUE TITLE
Pickle Error

### ISSUE THREAD

**Issue by pachacamac** [nadermx/backgroundremover#2]
Pickle is not the best choice for storing data like this. The problem is that pickle differs between Python versions. With Python 3.9 I'm getting this for example:

```
[...]/python3.9/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

See [here](https://nedbatchelder.com/blog/202006/pickles_nine_flaws.html) and [here](https://www.benfrederickson.com/dont-pickle-your-data) for more in depths explanations.

I have not tried those myself but it might be worth looking into cPickle or Joblib as an alternative. Not sure if they have the same issues.

**Comment by nadermx** [comment]
@pachacamac I went ahead and refactored and changed the import library process to gdown, https://github.com/nadermx/backgroundremover/commit/540f2af8cf87f92c10e01ed910028d2142e820f3 
Upgrade to the newest version and it should be fixed.
