### ISSUE TITLE
How to generate binary mask instead of cutout

### ISSUE THREAD

**Issue by shailenderjain** [nadermx/backgroundremover#21]
Hello,

Is there any option to generate a mask instead of cutout? I wanted to check if there is any command line option. I wanted to create background of different colors like RED, White, Blue, Black etc

Thanks
Shailender Jain

**Comment by FinallyKiKi** [comment]
Make matte key file (green screen overlay)
Make a matte file for premier

backgroundremover -i "/path/to/video.mp4" -mk -o "output.matte.mp4"
