### ISSUE TITLE
-tov/--transparentvideoovervideo: invalid <lambda> value:

### ISSUE THREAD

**Issue by j2l** [nadermx/backgroundremover#28]
Hi,
I tried multiple way to get a `-tv` working an example video to work with a background and it always throws the error in the title.

For instance, `backgroundremover -i "./stress.mp4" -tov "vert.mp4" -o "output.mp4"` results in:
`backgroundremover: error: argument -tov/--transparentvideoovervideo: invalid <lambda> value: 'vert.mp4'`

Weirdly enough `backgroundremover -i "./stress.mp4" -tov -o "output.mp4"` "works" ... but there's no overlay video input so I get:
`/<stdin>: No such file or directory
Process finished`

Any idea?

**Comment by celikmustafa89** [comment]
same issue:

`backgroundremover -i 15_terminator.mp4 -tov green.mp4 -o g_out.mov
usage: backgroundremover [-h] [-m {u2net,u2net_human_seg,u2netp}]
                         [-a [ALPHA_MATTING]]
                         [-af ALPHA_MATTING_FOREGROUND_THRESHOLD]
                         [-ab ALPHA_MATTING_BACKGROUND_THRESHOLD]
                         [-ae ALPHA_MATTING_ERODE_SIZE]
                         [-az ALPHA_MATTING_BASE_SIZE] [-wn WORKERNODES]
                         [-gb GPUBATCHSIZE] [-fr FRAMERATE] [-fl FRAMELIMIT]
                         [-mk [MATTEKEY]] [-tv [TRANSPARENTVIDEO]]
                         [-tov [TRANSPARENTVIDEOOVERVIDEO]]
                         [-toi [TRANSPARENTVIDEOOVERIMAGE]]
                         [-tg [TRANSPARENTGIF]]
                         [-tgwb [TRANSPARENTGIFWITHBACKGROUND]] [-i [INPUT]]
                         [-bi [BACKGROUNDIMAGE]] [-bv [BACKGROUNDVIDEO]]
                         [-o [OUTPUT]]
backgroundremover: error: argument -tov/--transparentvideoovervideo: invalid <lambda> value: 'green.mp4'`

**Comment by j2l** [comment]
So far, I didn't find a way to make it work and python code looks the same as `-tv` so I don't see why the file is not loaded as overlay.
Let me know @celikmustafa89 if you find some way :wink:

**Comment by celikmustafa89** [comment]
Hi,

I found the way of running it.

`backgroundremover -i terminator.mp4 -toi -bv green.mp4 -o out_vid.mov`

however the output is not good. I was expecting the original video with the green background but it is a grayscale output. :S :S

<img width="605" alt="image" src="https://user-images.githubusercontent.com/6848680/160607900-4b536fc7-92f8-49d2-895c-b185d28b6176.png">

**Comment by celikmustafa89** [comment]
> So far, I didn't find a way to make it work and python code looks the same as `-tv` so I don't see why the file is not loaded as overlay.
> Let me know @celikmustafa89 if you find some way 😉

Hi @edouard-mangel ,

I found the way of running it.

`backgroundremover -i terminator.mp4 -toi -bv green.mp4 -o out_vid.mov`

however the output is not good. I was expecting the original video with the green background but it is a grayscale output. :S :S

<img width="605" alt="image" src="https://user-images.githubusercontent.com/6848680/160607900-4b536fc7-92f8-49d2-895c-b185d28b6176.png">

**Comment by celikmustafa89** [comment]
may be it is because of the version of FFmpeg ?? I do not know.

**Comment by j2l** [comment]
I had the same, its the alpha matte (mask for the alpha channel).
For an image with the same size as the video it shrinks the video and only keep the matte:
![image](https://user-images.githubusercontent.com/65325/160610734-437de85a-d4b5-49c7-a337-87e65a279cf2.png)

**Comment by celikmustafa89** [comment]
> I had the same, its the alpha matte (mask for the alpha channel).
> For an image with the same size as the video it shrinks the video and only keep the matte:
> ![image](https://user-images.githubusercontent.com/65325/160610734-437de85a-d4b5-49c7-a337-87e65a279cf2.png)

how should we run the code to get a proper output? any idea?

**Comment by j2l** [comment]
> > I had the same, its the alpha matte (mask for the alpha channel).
> > For an image with the same size as the video it shrinks the video and only keep the matte:
> > ![image](https://user-images.githubusercontent.com/65325/160610734-437de85a-d4b5-49c7-a337-87e65a279cf2.png)
> 
> how should we run the code to get a proper output? any idea?

No idea :confused:

**Comment by j2l** [comment]
Oh, nice!
The matte is 0.4444 the scale of the original video in my case. Is it the same for you?
Maybe simply adding some scale parameter in ffmpeg could do the trick?

**Comment by j2l** [comment]
Your exact command worked for me!

![vlcsnap-2022-03-29-15h37m59s453](https://user-images.githubusercontent.com/65325/160624136-894577c1-81ed-4556-a511-da248de2e2d9.png)

**Comment by j2l** [comment]
Hey,it also works with a PNG image: `ffmpeg -i stress.mp4 -i matte.mp4 -i vert.png -filter_complex '[1][0]scale2ref[mask][main];[main][mask]alphamerge[vid];[2:v][vid]overlay[out]' -map [out] complete2.mp4
`

**Comment by celikmustafa89** [comment]
The following command generates a video that scale-up the video for the background image. It may help in some cases. At least work for me. I spent some time writing this command, just want to share it to save your time if you need it.

`ffmpeg -i test_fightclub.mp4 -i fight_matte_image.mov -i green.png -filter_complex '[1][0]scale2ref[mask][main];[main][mask]alphamerge[vid];[vid][2:v]scale2ref[fg][bg];[bg][fg]overlay[out]' -map [out] fight_image_complete_scale2ref.mp4`

my output was like this:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/6848680/160844756-a23bd263-c0a3-4826-9993-a0526b0ec266.png">

now I can generate following output with the code:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6848680/160844904-ef2a634b-b029-4eff-8fe8-b5af5465a737.png">

**Comment by j2l** [comment]
Cool!
Thank you!

**Comment by nadermx** [comment]
I had this open on superuser as I had gotten stuck.   I'll fix the '-tov' ffmpeg command and close this issue.

**Comment by j2l** [comment]
Thank you!
