### ISSUE TITLE
Unsupported hardware error is misleading

### ISSUE THREAD

**Issue by levovix0** [nadermx/backgroundremover#3]
```
[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
```
CPU: AMD A8-7650K Radeon R7 4C+6G (4) @ 3.300GHz
GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M
OS: Manjaro Linux
Drivers: free

**Comment by levovix0** [comment]
The program works, but it is not obvious after this error.

Probably add `Warning:` before error message?

**Comment by nadermx** [comment]
This is related to your GPU and pytorch, This [thread](https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518/2) shows to to hide it, they suggest 

> You can pass USE_NNPACK=0 to the setup.py following the instructions to build from source from [here](https://github.com/pytorch/pytorch#from-source)
