### ISSUE TITLE
Speed: Slow processing in ubuntu

### ISSUE THREAD

**Issue by alagiyanirav** [nadermx/backgroundremover#30]
I have 8 GB RAM Ubuntu in EC2. The image background removal command is taking time around 6-10 seconds but My CPU & RAM is utilizing only 1-10 % 

Is there any option to increase the speed via utilizing more resources?

I really appreciate support of this repo.

**Comment by nadermx** [comment]
For Video or image?

**Comment by alagiyanirav** [comment]
It is from Image.

**Comment by nadermx** [comment]
Try newest version

**Comment by alagiyanirav** [comment]
Thanks for the reply. But How to know the existing version and the new version?
 backgroundremover -v command is not working. 
Also, How to update it using cli?
