### ISSUE TITLE
[Windows] no file output after ffmpeg frame conversion complete

### ISSUE THREAD

**Issue by Chad90b** [nadermx/backgroundremover#33]
>backgroundremover -i t1.mp4 -tv -o t2.mp4

FINISHED ALL FRAMES (135)!
Starting alphamerge
after call

on windows after completing all frames and about to merge nothing happens. temp dir is cleaned. no error occurs but the user is thrown out of the program from the terminal and the output file remains empty at 0 bytes. its like the program forgot to actually write the data to the output location before ending

![image](https://user-images.githubusercontent.com/68355086/162640310-49bf6483-017e-432d-b8f3-bd950723d07b.png)

**Comment by nadermx** [comment]
This is an issue with windows file naming.  I slowly getting around to it.  There are other issues open with this, I think #1 or #2.

**Comment by Chad90b** [comment]
@nadermx i apologize for not noticing those. thank you for the feedback. we can probably just close this issue then - right?

**Comment by nadermx** [comment]
Ill close it when i or someone fixes the issue

**Comment by jshargrave** [comment]
Any chance this will get fixed? Or is there a workaround?

**Comment by AlonDan** [comment]
Join the question, I'm curious if somebody fixed it? 
I'm getting a 0 Byte sized file named: "output.mov"

**Comment by jshargrave** [comment]
I tried doing it on linux but the dependencies changes so much now have syntax errors. I'm guessing this project isn't being maintained anymore

**Comment by nadermx** [comment]
I should have a commit today for this I hope.  Windows uses different
folder structure than linux, so have to add a exception

**Comment by nadermx** [comment]
I am working on this now, as it should close, https://github.com/nadermx/backgroundremover/issues/8 as well.  Once I get something live I will ask one of you with windows to try.

**Comment by nadermx** [comment]
Could some one on windows try installing the most recent version of this repo and letting me know if it works now?

`pip install git+https://github.com/nadermx/backgroundremover.git@09c142c8ebcaee035dbd867248957bfbc87e8e3f`

As I do not have a windows system to try.

**Comment by AlonDan** [comment]
> Could some one on windows try installing the most recent version of this repo and letting me know if it works now?
> 
> `pip install git+https://github.com/nadermx/backgroundremover.git@2a7421970591a12f57f275079e54febe9dd3c287`
> 
> As I do not have a windows system to try.

I just tried it, unfortunately it still creates an "output.mov" which is 0 Byte size. 

Let me know if you want to test again, I'll be happy to test whenever I see your message :)

**Comment by nadermx** [comment]
I'm working on as many issues as I can this month and will commit by the
30thish.

**Comment by g5fighter** [comment]
I'm having the same issue, the video output for -tv is empty

This is my command:

`backgroundremover -i "30fps.mp4" -m "u2net_human_seg" -fr 30 -tv -o "output2.mov"`

**Comment by nadermx** [comment]
Windows?

**Comment by g5fighter** [comment]
> 

Yes
