### ISSUE TITLE
API docs or JavaScript example

### ISSUE THREAD

**Issue by aubergene** [nadermx/backgroundremover#35]
I'm trying to use the service from the browser with JavaScript and am having trouble understanding the API from the Python example. Would it be possible to add a JavaScript example using `fetch` or perhaps general http request documentation. Thanks

**Comment by nadermx** [comment]
I will be adding in more languages to the docs here soon.

**Comment by artzie92** [comment]
Hi @nadermx. How looks progress in js support :)?

**Comment by nadermx** [comment]
I must say, for support requests, these follow ups are tolerable.  I'll dedicate some time this month and close up some of these issues

**Comment by samry** [comment]
@nadermx any chance we could get an update here? 

Purchased a monthly plan and would love to use it, but just can't hack it in Javascript or CURL.

**Comment by nadermx** [comment]
https://backgroundremover.app/api/?javascript#g-i18n-simply_replace-safe
