### ISSUE TITLE
How to use this on GPU?

### ISSUE THREAD

**Issue by arunpatro-meesho** [nadermx/backgroundremover#36]
I couldn't find a flag to enable this to run on GPU. Can anyone help?

**Comment by conrad10781** [comment]
There isn't one, that would be handled by PyTorch ( https://pytorch.org/ ). If you're running on Linux, this will be smoother with an Nvidia card compared to one with AMD though.

**Comment by nadermx** [comment]
GPU is enabled by default, if you do not have a GPU is uses CPU
