### ISSUE TITLE
Windows + Anaconda = Won't show process + Bulk Related Question 

### ISSUE THREAD

**Issue by AlonDan** [nadermx/backgroundremover#37]
Just to be clear, I'm not a programmer but I've noticed that compare to other repos I tried on my local machine while testing your awesome repo.

Usually when processing (anything) it shows on Anaconda Prompt (or any console using) either progress bar with percentage and some information while it's "cooking" but in this one it won't show anything on windows and anaconda at least.

So when I run for example:
`backgroundremover -i ./_SOURCE_/image.jpg -o ./_RESULT_/output.png`

It will show the blinking underscore  _ 

and it works but no indication how much time it takes, or any info that could be helpful while it's processing.

So either I'm doing something wrong, or it's just not in the code for now on windows at least?

If it's not there yet, will you please consider to add this process status, it sure give some indication such as time estimate or how long it runs and the percentage of each task (image, multiple images or video when it will work on windows of course).

- 

**Another question:** (multiple images / bulk)
Please consider that I'm not a programmer so I don't know how to mess with the code.
Is there a parameter I can add when I run "backgroundremover " so it will run ALL images on my input directory? 

If not, will you consider to add such parameter? (could be cool for both multiple images, and videos) instead of testing one by one.

Thanks ahead for replying, keep up the good work! 👍

**Comment by nadermx** [comment]
The bulk was a request in issue https://github.com/nadermx/backgroundremover/issues/22, they put a piece of code there to do that while I work on the native path upload currently

**Comment by AlonDan** [comment]
> The bulk was a request in issue #22, they put a piece of code there to do that while I work on the native path upload currently

Thanks for the quick reply, I tried that.. but couldn't make it to work I'm not a programmer and it was confusing me... maybe if later on you'll add it as extra parameter it will be much easier to use even for newbies like me. :)

**Comment by AlonDan** [comment]
I hope you can read what I asked about the Process status and share if there are any planse,
BTW - I'm willing to help testing any Windows + Anaconda so feel free to message me if you like to test new improvements or experiments in general.

I hope you can improve the processing as it's blindly waiting without have no indication at all.
I'm curious if it does work for Linux but not for Windows / Anaconda (yet).

**Comment by nadermx** [comment]
Try the new version, should work on windows `pip install --upgrade backgroundremover`
