### ISSUE TITLE
how to run background remove from a python file?

### ISSUE THREAD

**Issue by orydatadudes** [nadermx/backgroundremover#42]
how can i use that code for removing background from an image i have inside my python script code

**Comment by ahmad88me** [comment]
Yes, I created a pull request with an example in the readme here: https://github.com/nadermx/backgroundremover/pull/138

**Comment by nadermx** [comment]
Fixed in this release, https://github.com/nadermx/backgroundremover/commit/123d4445808c25521d06611e6e7e3aa9bb426b2f  read the ReadMe for a howto
