### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by Praveensenpai** [nadermx/backgroundremover#45]
DEPRECATION: Pillow is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [192 lines of output]
      running install
      C:\Apps\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-310\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "C:\Users\Senpai\AppData\Local\Temp\pip-install-gd05bu7l\pillow_2e009652622f47769adc0b882b02cfc5\setup.py", line 865, in <module>
          setup(
        File "C:\Apps\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
          return run_commands(dist)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
          dist.run_commands()
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Apps\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Apps\Python310\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\command\install.py", line 695, in run
          self.run_command('build')
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Apps\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Apps\Python310\lib\site-packages\setuptools\command\build.py", line 24, in run
          super().run()
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Apps\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Apps\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Apps\Python310\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Apps\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\Senpai\AppData\Local\Temp\pip-install-gd05bu7l\pillow_2e009652622f47769adc0b882b02cfc5\setup.py", line 702, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Senpai\AppData\Local\Temp\pip-install-gd05bu7l\pillow_2e009652622f47769adc0b882b02cfc5\setup.py", line 922, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      C:\Users\Senpai\AppData\Local\Temp\pip-install-gd05bu7l\pillow_2e009652622f47769adc0b882b02cfc5\setup.py:44: RuntimeWarning: Pillow 8.1.1 does not support Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of Pillow
  Moving to c:\apps\python310\lib\site-packages\pil\
   from C:\Apps\Python310\Lib\site-packages\~il
  Moving to c:\apps\python310\lib\site-packages\pillow-9.3.0.dist-info\
   from C:\Apps\Python310\Lib\site-packages\~illow-9.3.0.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AnaStepic** [comment]
I'm getting the same error.

**Comment by FlawLessx** [comment]
Install required library for pillow

`sudo apt install zlib1g-dev libjpeg-dev libpng-dev`

**Comment by garyakimoto** [comment]
me2, it is because pillow problem...

**Comment by nadermx** [comment]
If you install from git it should work.  I havent run tests for version .2,
but the requiremnts file says pillow== vs =>

**Comment by nadermx** [comment]
try newest release https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1
