### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hakxcore** [nadermx/backgroundremover#46]
The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by nadermx** [comment]
try newest release https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1
