### ISSUE TITLE
Which Python version

### ISSUE THREAD

**Issue by av01d** [nadermx/backgroundremover#47]
What Python version should I use for this library to work?
On the github page it says (under Requirements): python <= 3.6
But browsing through some issues, it seems backgroundremover might work on newer versions as well?
What is the minimum (and maximum?) Python version for this tool?
While you're at it... maybe update the requirements section as well? Thanks!

**Comment by nadermx** [comment]
I thought it was clear, python <= 3.6  means python 3.6 or greater.
Although I have not tried with python 3.11

**Comment by av01d** [comment]
I read `python <= 3.6` as Python version 3.6, or smaller.
Don't you mean `python >= 3.6`?

**Comment by nadermx** [comment]
fixed, tx.

**Comment by av01d** [comment]
Thanks a lot!

**Comment by av01d** [comment]
I can confirm that it installs flawlessly on python 3.9.2 (Debian 11).
