### ISSUE TITLE
Video Error / Failed

### ISSUE THREAD

**Issue by AlonDan** [nadermx/backgroundremover#48]
I'm trying to test video but I get some errors.
Any idea how can I fix this and make it work?

I'm not a programmer so please help / guide step-by-step if possible, 
Thanks ahead! 💙

- I use Anaconda on Windows 10

![cmd_2023-01-14_06-01-08](https://user-images.githubusercontent.com/21152334/212449863-734c3ae4-fadb-422b-a16b-adff54623c56.png)

**Comment by nadermx** [comment]
Try newest release, https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1 Also make sure you have ffmpeg 4.4+ installed
