### ISSUE TITLE
No longer active?

### ISSUE THREAD

**Issue by boxabirds** [nadermx/backgroundremover#50]
Looks like backgroundremover is no longer maintained and the service is not active. I paid up front for access to the service but it remains stuck in status "inactive". Also there seems to be no engagement on Github issues including bugs where the output from sample code is corrupted.

It's a shame it looks promising.

**Comment by nadermx** [comment]
Its active.  I just very slowly have been working on 0.2.  It should work
on everything but windows, as I have no windows machine to test on.  If you
refer to the site, that is live as well, but migrating it this week

**Comment by boxabirds** [comment]
Ok thank you. But I've had a plan that has been in status "not active" for
several weeks now and I have had no luck with example usage output on Mac
see https://github.com/nadermx/backgroundremover/issues/49

**Comment by nadermx** [comment]
Ah, open source, you get what you pay for.  You could also learn to code yourself and help advance the issues you may have.  I am sure on the next update I Will cover most of those, but yes, making a MP4 to a MOV is a significant size difference.  But the MP4 container does not support transparent background.

**Comment by boxabirds** [comment]
Sure I get that -- and it's great you open sourced it, but actually for the
subscription plan, I didn't pay for open source -- I paid for a plan that
would be active and an endpoint that would do what it promised.

**Comment by nadermx** [comment]
Ah, you speak of the app.  I pushed an update yesterday that broke that.  I will fix that hopefully today.

**Comment by nadermx** [comment]
But worse case, you can also auto refund yourself https://backgroundremover.app/refund/

**Comment by boxabirds** [comment]
Yes. It was broken when I signed up last week: status “inactive”
