### ISSUE TITLE
Is there a way to run bgremover on windows?

### ISSUE THREAD

**Issue by 343intact** [nadermx/backgroundremover#52]
The term "backgroundremover" is not recognized, is there another way to use it?

**Comment by 343intact** [comment]
The term "background" is not recognized, is there another way to use it?

**Comment by Develeone** [comment]
`python -m backgroundremover.cmd.cli -i "in.jpg" -a -ae 15 -o "output.png"`

**Comment by 343intact** [comment]
> `python -m backgroundremover.cmd.cli -i "input.jpg" -a -ae 15 -o "output.png"`

Thank you!
