### ISSUE TITLE
Error with Pillow. Can we build the package locally?

### ISSUE THREAD

**Issue by hamoid** [nadermx/backgroundremover#54]
Hi, when I run

    $ pip install backgroundremover

it fails because Pillow 8.1.1 fails to install on my system with this error

    if pd is not None and pd.key == self.egg_name.lower():
      AttributeError: 'PathDistribution' object has no attribute 'key'

If I do

    $ pip install pillow

I get version 9.4.0 fine.

Could I update that dependency in `requirements.txt` and build the package locally? Or version 8.1.1 is required? I don't know how to build it, not experienced with Python. Thank you :)

Update: actually I tried https://github.com/danielgatis/rembg and it worked for me. I wonder how do both projects differ...

**Comment by nadermx** [comment]
try newest release https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1
