### ISSUE TITLE
Error while input mp4 file: nb_frames attribute not present in video stream

### ISSUE THREAD

**Issue by AqueelAhmedV** [nadermx/backgroundremover#57]
Relevant part of the error message:
```python
"<HOMEDIR>/.local/lib/python3.8/site-packages/backgroundremover/utilities.py", line 80, in matte_key
    total_frames = int(info["streams"][0]["nb_frames"])
KeyError: 'nb_frames'
```
I think some video streams wont have nb_frames attribute and the no. of frames will have to be obtained in a different way, Please fix this error.

**Comment by nadermx** [comment]
What version of ffmpeg are you using?
