### ISSUE TITLE
pip install backgroundremover fails with weird dependency issues

### ISSUE THREAD

**Issue by fmmarzoa** [nadermx/backgroundremover#58]
Hi there,

When I run pip install backgroundremover in my Mac, it seems to try to install several different versions of backgroundremover for no apparent reason, and ends up failing.

.1.4, backgroundremover==0.1.5, backgroundremover==0.1.6, backgroundremover==0.1.7, backgroundremover==0.1.8 and backgroundremover==0.1.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    backgroundremover 0.1.9 depends on torch>=1.7.0
    backgroundremover 0.1.8 depends on torch>=1.7.0
    backgroundremover 0.1.7 depends on torch>=1.7.0
    backgroundremover 0.1.6 depends on dataclasses==0.8
    backgroundremover 0.1.5 depends on torch>=1.7.0
    backgroundremover 0.1.4 depends on torch>=1.7.0
    backgroundremover 0.1.3 depends on torch>=1.7.0
    backgroundremover 0.1.2 depends on torch>=1.7.0
    backgroundremover 0.1.1 depends on torch>=1.7.0

% pip --version
pip 23.0.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)

Regards,
Fran

**Comment by nadermx** [comment]
Please try newest release https://github.com/nadermx/backgroundremover/releases/tag/v0.2.1
