### ISSUE TITLE
Commercial version API endpoint is not working

### ISSUE THREAD

**Issue by galipmedia** [nadermx/backgroundremover#59]
Hi I paid for credits and it was working fine, then it just stopped working the api endpoint returns an html...

```
<body>
	<h1>Not Found</h1>
	<p>The requested resource was not found on this server.</p>
</body>

```

**Comment by nadermx** [comment]
Should be fixed

**Comment by galipmedia** [comment]
Thanks

**Comment by galipmedia** [comment]
Seems the api is not working again ? api endpoint seems to be down

**Comment by nadermx** [comment]
Just tested, Seems to be fine.  No alerts of it going down either.  What
issue are you having again?

**Comment by galipmedia** [comment]
Using node request I am getting 
```
error Error: getaddrinfo ENOTFOUND api.backgroundremover.app
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.backgroundremover.app'
}

```

**Comment by nadermx** [comment]
Please change domain to backgroundremoverai.com

**Comment by nadermx** [comment]
Api.backgroundremoverai.com i mean.  Also I believe if you check the node
code if you follow the url that takes you too might be updated.

**Comment by galipmedia** [comment]
Thanks for the quick reply.
