### ISSUE TITLE
TLD SSL issue

### ISSUE THREAD

**Issue by jwang919** [nadermx/backgroundremover#61]
Hi, using the js version, getting Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.backgroundremover.app. is not in the cert's altnames: DNS:api.backgroundremoverai.com

**Comment by jwang919** [comment]
Also, how can I pass in an image via an online url (vs a local image?)

**Comment by jwang919** [comment]
Please let me know! I would love to use your API :)

**Comment by nadermx** [comment]
Hi, we changed domains, please update code to https://backgroundremoverai.com/api/#settings-i18n-introduction

**Comment by jwang919** [comment]
Thank you nadermx! :) 

So I successfully got the result
url: '/static/downloads/d37317089f3d40349ea1d81f12b0ba89/blob.png',
Are we supposed to be able to access this at "https://api.backgroundremoverai.com/v1/results/static/downloads/d37317089f3d40349ea1d81f12b0ba89/blob.png"?
Or how does it get stored locally?

**Comment by JoeGarcia2** [comment]
Same question as above. How do you accesst the file after API conversion returns '/static/downloads......'?

**Comment by nadermx** [comment]
I am not sure I am understanding.  The API code, should save that to a local folder 
```
    if finished:
        for f in data.get('files'):
            download_file("%s" % f.get('url'), "%s" % f.get('filename'))
        return {"finished": "files downloaded"}
```

That url should keep the file accesible till its delete from the server but the api script should be saving it to local

**Comment by JoeGarcia2** [comment]
Ignore the last question. I figured it out. The resulting image is located at: https://api.backgroundremoverai.com/static/downloads/
The convert endpoint had domain: https://backgroundremover.app so I was looking for the image at https://backgroundremover.app/static/downloads/
My mistake

**Comment by nadermx** [comment]
That must of been old code, so you updated it and its fine?

**Comment by JoeGarcia2** [comment]
Yes. All good. Thanks for the fast reply.
