### ISSUE TITLE
Remove non-text background

### ISSUE THREAD

**Issue by dnth** [nadermx/backgroundremover#63]
I'd like to remove only the non-text background. Can this be done?

For example, I'd like to remove the background of this image and keep the lyrics text 
![image](https://user-images.githubusercontent.com/6821286/227842534-5f4f080e-2e76-47b1-acfc-623863ad8a67.png)

**Comment by sunkangchina** [comment]
If you just want go get text 
you can try some ocr project.
ocr is for get text.
i didn't got backgroundremover has get lyrics text.

**Comment by nadermx** [comment]
Yeah, I think what you want is OCR for this https://github.com/tesseract-ocr/tesseract
