### ISSUE TITLE
using the -tv argument does not work from WSL

### ISSUE THREAD

**Issue by edouard-mangel** [nadermx/backgroundremover#8]
Hi, 
I've been trying to use the soft from WSL, the mask creation with -mk argument seems fine, but everytime I try to remove background with the -tv argument, the output file weighs 0kB. 

I don't have error in the console, or anything like that, how do you think I can fix this?

**Comment by nadermx** [comment]
Not sure what WSL is? Windows? Also, what version of FFMPEG do you have, this needs 4.4+

**Comment by edouard-mangel** [comment]
Yes, it's Windows Subsystem for Linux. 
I did in fact not have the 4.4 version of ffmpeg (forgot I could add a PPA myself, it's been a while since I used GNU/Linux), but I do now have ffmpeg-4.4 and the problem stays the same.

**Comment by nadermx** [comment]
I think it has to do something with the temporary files created in windows.  Seems the temporary directory does this in ubuntu vs windows 
```
On Windows, the directories C:\TEMP, C:\TMP, \TEMP, and \TMP, in that order.
On all other platforms, the directories /tmp, /var/tmp, and /usr/tmp, in that order.
```
So it might be something with where I'm saving the directory that works fine on ubuntu but windows is changing location

**Comment by nadermx** [comment]
also, did you install the python3-x-dev (x being what ever version you are using)?

**Comment by edouard-mangel** [comment]
Hello, 
Yes I have the ffmpeg4.4, python3.9-dev packages, but I don't have a C:\TMP or TEMP folder, but the console outputs "Output #0, mp4, to '/tmp/tmpdexkumo3/matte.mp4':"
I tried copying the file in a folder I have access to, and the file keeps a size of 44bytes. 

How can I investigate some more ?

**Comment by edouard-mangel** [comment]
the problem does not lie in the file i'm trying to remove the background from, because it works if I use your website by the way.

**Comment by nadermx** [comment]
try `apt-get install -y build-essential`

**Comment by nadermx** [comment]
@edouard-mangel I think I found this, if you can edit it locally and try? Seem it is a issue with temp file and windows, https://stackoverflow.com/a/8577226/4180276

**Comment by nadermx** [comment]
Let me know if this fixes it
`pip install git+https://github.com/nadermx/backgroundremover.git@09c142c8ebcaee035dbd867248957bfbc87e8e3f`
