### ISSUE TITLE
Can you make it compatible with python3.8 and other latest versions of python.

### ISSUE THREAD

**Issue by imprintnext-deb** [nadermx/backgroundremover#81]
Can you make it compatible with python3.8 and other latest versions of python.

**Comment by nadermx** [comment]
It is... read me says python 3.6 or greater

**Comment by imprintnext-deb** [comment]
I am getting an error in python3.8. Can you help me on this. You can check the screenshot below.

![image](https://github.com/nadermx/backgroundremover/assets/81958754/0ff89e60-2103-4a90-a620-222c2c837c01)
