### ISSUE TITLE
#81 | I am getting an error in python3.8. Can you please check this.

### ISSUE THREAD

**Issue by imprintnext-deb** [nadermx/backgroundremover#82]
#81 | I am getting an error in python3.8. Can you please help me on this. You can check the screenshot below.

![image](https://github.com/nadermx/backgroundremover/assets/81958754/d9e9ed92-2e44-4fa6-875b-1b33b7b27932)

**Comment by nadermx** [comment]
Can you please try installing from the github, and trying again.  IE, pip install git+github.com/nadermx/backgroundremover should install the commit I just tried.  If it works, let me know so I can close the issue

**Comment by imprintnext-deb** [comment]
Still I am getting the same error. Is there anything else that I am missing.

Here is my screenshot:

![image](https://github.com/nadermx/backgroundremover/assets/81958754/50e646b0-6257-4e6f-8188-3028627e5f99)



![image](https://github.com/nadermx/backgroundremover/assets/81958754/9dc12a71-59c0-423f-8070-6888a2631768)

**Comment by nadermx** [comment]
That still seems like the old one.  Try installing to specific git.

**Comment by nadermx** [comment]
make sure you remove backgroundremover first, then fresh install pip
install git+https://github.com/nadermx/backgroundremover.git
@86d4c591a17b8bc99ca998073b7d5d12372c4be7

**Comment by nadermx** [comment]
I went ahead and bumped the version, so `pip install --upgrade backgroundremover` should fix it
