### ISSUE TITLE
why does it access google driver?

### ISSUE THREAD

**Issue by OsmondGao** [nadermx/backgroundremover#9]
`  File "d:\prog\python\36\lib\site-packages\backgroundremover\utilities.py", line 295, in download_file_from_google_drive
    gdown.download(URL, path, quiet=False)
  File "d:\prog\python\36\lib\site-packages\gdown\download.py", line 114, in download
    res = sess.get(url, headers=headers, stream=True)
  File "d:\prog\python\36\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "d:\prog\python\36\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\prog\python\36\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "d:\prog\python\36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002225602D4E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))`

**Comment by nadermx** [comment]
It access google drive, if you do not have the u2net models in you're `~/.u2net` path.  You can get them from baidu here. https://pan.baidu.com/s/1WjwyEwDiaUjBbx_QxcXBwQ

**Comment by nadermx** [comment]
I'm working on a pull request, and i reopened the issue I have with the, but in the mean time, you can get [u2net](https://github.com/xuebinqin/U-2-Net/issues/236) from here  https://video.backgroundremover.app/static/u2net/u2net.pth https://video.backgroundremover.app/static/u2net/u2net_human_seg.pth

**Comment by nadermx** [comment]
Went ahead and closed this, as I got the model in the github repo

**Comment by liujin163** [comment]
> It access google drive to download them, if you do not have the u2net models in your `~/.u2net` path. You can get them from baidu here. https://pan.baidu.com/s/1WjwyEwDiaUjBbx_QxcXBwQ I'll see if I can add a fallback for baidu, but I don't have any experience with them..

the download url need access code, cloud you please send it for me?
