### ISSUE TITLE
Why am I getting 320x320 output?

### ISSUE THREAD

**Issue by ydyote** [nadermx/backgroundremover#93]
Cool software man,

I tried the other mode too but that didn't work properly, but I saw an issue for that

but when I run with params -i "video.mp4" -mk -o "output.mov" I get 320x320 output.

can this be somehow configured to match the source video resolution?

Thanks

**Comment by nadermx** [comment]
If you want to see why the 320 comes out, and the reason it does not matter, see https://github.com/danielgatis/rembg/issues/75#issuecomment-774514965

**Comment by ydyote** [comment]
Thanks for the fast reply,

Ok so its downscale because of DNN so better quality output is not technically possible

but in theory there could be added scaling via ffmpeg and idk whether one can also smooth it out a bit.. but I guess one could write a script for that themselves
