### ISSUE TITLE
RuntimeError: storage has wrong byte size

### ISSUE THREAD

**Issue by Desmond-Campbell** [nadermx/backgroundremover#97]
My sequence of commands on 4 different Ubuntu 22 boxes below. I'm about to try on a lower version of Ubuntu.

`sudo apt install ffmpeg python3.10` 
or `sudo apt install ffmpeg python3.10-dev`

`sudo apt install pip`

`pip install backgroundremover`

`backgroundremover -i "/path/to/image.jpeg" -o "output.png"` 
or `backgroundremover -i "/path/to/image.jpeg" -m "u2net" -o "output.png"` 
or `backgroundremover -i "/path/to/image.jpeg" -m "u2net_human_seg" -o "output.png"` 
or `backgroundremover -i "/path/to/image.jpeg" -m "u2netp" -o "output.png"`

I got this error on all the boxes.

```
Traceback (most recent call last):
  File "/usr/local/bin/backgroundremover", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/cmd/cli.py", line 239, in main
    remove(
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/bg.py", line 183, in remove
    model = get_model(model_name)
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "/usr/local/lib/python3.10/dist-packages/backgroundremover/u2net/detect.py", line 82, in load_model
    torch.load(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
**RuntimeError: storage has wrong byte size: expected %ld got %ld-2384061055873887482048**
```

**Comment by nadermx** [comment]
Why is there an or? Should first install python and then install
python3.10-dev

**Comment by nadermx** [comment]
Ah okay, might need more memory to run it?

**Comment by nadermx** [comment]
can you remove the background from the image using
backgroundremoverai.com/image ?

**Comment by nadermx** [comment]
Just to clarify, you installed on what ever box python3.x-dev (what ever version, so say python3.8-dev if you have python3.8, or in the other python3.10-dev)

**Comment by nadermx** [comment]
I just tried it with python3.10 after installing python3.10-dev it worked, 
![image](https://github.com/nadermx/backgroundremover/assets/7340380/be5c3538-1e8e-4eed-a56f-9279fe218840)

**Comment by nadermx** [comment]
![image](https://github.com/nadermx/backgroundremover/assets/7340380/5e3cf4ae-5c93-477d-9a82-9347f4b062af)

**Comment by nadermx** [comment]
So you did not clarify.  First in stalled say python3.10, then you ran `sudo apt install python3.10-dev` or did you just run `sudo apt install python3-dev`?

**Comment by nadermx** [comment]
Once again you must install `python3.10-dev` and you seem to gloss over the thing that is in the read me and repeated  in this thread.  Please run `sudo apt install python3.10-dev` or what ever version of python you are using.

**Comment by nadermx** [comment]
So, as I said imideatly after you queston "Why is there an or? Should first install python and then install
python3.10-dev"  So I am unsure how else to make it clear that after installing python you have to install pythin3.10-dev and then install backgroundremover.

**Comment by nadermx** [comment]
Or what ever version of python you installed, so say for example if you install python3.8 then you must install python3.8-dev, or in your case it showed python3.10 so then python3.10-dev

**Comment by nadermx** [comment]
I'm gonna close the issue, reopen if its still an issue
